# Generated by Django 5.0.6 on 2024-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
