# Generated by Django 5.0.6 on 2024-07-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
