# Generated by Django 5.0.6 on 2024-07-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_district',
            field=models.CharField(default='Unknown District', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_housename',
            field=models.CharField(default='Unknown Housename', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_mob',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(default='Unknown Name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_pincode',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_place',
            field=models.CharField(default='Unknown Place', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_postoffice',
            field=models.CharField(default='Unknown Postoffice', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_state',
            field=models.CharField(default='Unknown State', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('others', 'others')], default='home', max_length=50),
        ),
    ]
